### ISSUE TITLE
placeholder from other plugin/expansion doesn't work

### ISSUE THREAD

**Issue by kokqi** [denniemok/staff-chat-simplified#1]
![image](https://github.com/denniemok/staff-chat-simplified/assets/78592988/e8674d88-36ea-446f-8557-eeee8503022d)

**Comment by kokqi** [comment]
and could you implement /sctoggle on and /sctoggle off

**Comment by kokqi** [comment]
basically just toggle the chat without the need of typing /staffchat <message> just <message>

**Comment by kokqi** [comment]
Could you implement commands like /sctoggle on and /sctoggle off? This would allow users to toggle the staff chat on and off quickly for chatting without the need to type /staffchat message every time

**Comment by kokqi** [comment]
and support any placeholder/expansion

**Comment by denniemok** [comment]
@kokqi Thanks for the suggestions and sorry for the long wait! Just recently got some time to look into this. I will release a new version in a few days to address your concerns.

**Comment by denniemok** [comment]
@kokqi You may try out the latest build [#1.0.5](https://github.com/denniemok/staff-chat-simplified/releases/tag/1.0.5).
